// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-evepass-core.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "EvepassCoreSpec.h"

@interface EvepassCore : NSObject <NativeEvepassCoreSpec>
#else
#import <React/RCTBridgeModule.h>

@interface EvepassCore : NSObject <RCTBridgeModule>
#endif

@end