// Bridge to evepass-core over the UniFFI React Native module.
//
// `uniffi-bindgen-react-native` generates a TypeScript module from the same core
// crate the desktop/CLI use; this file re-exports a typed, ergonomic surface for
// the screens. The vaultKey stays inside the `Session` (Rust) — the biometric
// export/import functions live in the NATIVE modules (Swift/Kotlin), never here.
//
// NOTE (scaffold): the import path below points at the generated module, which
// is produced when you run the bindgen against `core/`. Types mirror the Rust
// records in `evepass-core`.
import * as core from "evepass-core"; // generated by uniffi-bindgen-react-native

export interface KdfParams {
  alg: string;
  m: number;
  t: number;
  p: number;
}

export interface NewAccount {
  kdfSalt: Uint8Array;
  kdfParams: KdfParams;
  authKeyB64: string;
  wrappedVaultKey: Uint8Array;
  wrappedVaultKeyRecovery: Uint8Array;
  recoveryCode: string;
  publicKey: Uint8Array;
  signingPublicKey: Uint8Array;
  wrappedPrivateKeys: Uint8Array;
}

// A live, unlocked session (opaque handle into Rust).
export type Session = core.Session;

export const evepass = {
  createAccount: (password: string): NewAccount => core.createAccount(password),

  // Two-step login (Argon2id once). begin → sign in with authKey → complete.
  beginLogin: (password: string, salt: Uint8Array, params: KdfParams) =>
    core.beginLogin(password, salt, params),

  // Item crypto (plaintext crosses only for display/edit).
  encryptItem: (session: Session, itemJson: string) => session.encryptItem(itemJson),
  decryptItem: (session: Session, envelope: Uint8Array) => session.decryptItem({ envelope }),

  generatePassword: (
    length: number,
    upper: boolean,
    lower: boolean,
    digits: boolean,
    symbols: boolean,
  ) => core.generatePassword({ length, upper, lower, digits, symbols }),

  totpNow: (otpauthUri: string) => core.totpNow(otpauthUri),

  // Health / smart views (Fase 2 helpers).
  passwordScore: (password: string) => core.passwordScore(password),
};

// ⚠️ Deliberately NOT bridged to JS: exportVaultKey / sessionFromVaultKey.
// Those move the raw vault key to/from the secure enclave and are called only by
// the native biometric modules (BiometricVault.swift / BiometricVault.kt).
