// Generated by uniffi-bindgen-react-native
#include "react-native-evepass-core.h"
#include "generated/evepass_core.hpp"

namespace evepasscore {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeEvepassCore::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}